import ContactForm from "./contact-form";
import ContactNavLink from "./contact-nav-link";
import FaqSection from "./faq-section";
import Link from "next/link";
import { spanishArticles } from "./articles";
import { siteUrl } from "./site-config";
import YouTubeVideo from "./youtube-video";

const facts = [
  ["264,87 m²", "área del lote catastral"], ["Servicio", "habitación y baño independientes"],
  ["Terraza", "con jardín interior"], ["Local", "actualmente arrendado"],
];
const propertySpecs = [
  ["levels", "5", "niveles"], ["bed", "7", "habitaciones"],
  ["bath", "6", "baños"], ["area", "540 m²", "área construida"],
] as const;

function SpecIcon({name}:{name:typeof propertySpecs[number][0]}) {
  if(name==="levels") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 15 8 4 8-4M4 10l8 4 8-4M4 5l8 4 8-4-8-4-8 4Z"/></svg>;
  if(name==="bed") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 18v-8m18 8v-6a2 2 0 0 0-2-2H9a3 3 0 0 0-3 3v5m0-8V7h5a2 2 0 0 1 2 2v1M3 15h18M5 21v-3m14 3v-3"/></svg>;
  if(name==="bath") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 13h16v2a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5v-2Zm2 0V6a3 3 0 0 1 6 0M7 20l-1 2m11-2 1 2"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V8h16v12H4Zm4 0v-6h8v6M2 8l10-5 10 5M8 10h.01M12 10h.01M16 10h.01"/></svg>;
}
const gallery = [
  ["/casa/fachada-cielo-azul.webp", "Fachada de la casa durante el día", 1448, 1086],
  ["/casa/entrada-luces-calidas.webp", "Entrada principal con terraza y plantas", 1536, 1024],
  ["/casa/sala-principal.webp", "Sala principal con muebles de la familia", 1448, 1086],
  ["/casa/sala-complementaria.webp", "Vista complementaria de la sala principal", 1434, 1097],
  ["/casa/cocina-principal.webp", "Cocina con comedor auxiliar y techo en madera", 1433, 1098],
  ["/casa/cocina-complementaria.webp", "Vista general de la cocina", 1875, 839],
  ["/casa/cocina-mesones.webp", "Mesones y zona de trabajo de la cocina", 1825, 862],
  ["/casa/patio-luces.webp", "Patio interior con vegetación e iluminación cálida", 1434, 1097],
  ["/casa/terraza-atardecer.webp", "Terraza exterior al atardecer", 1434, 1097],
  ["/casa/habitacion-principal.webp", "Habitación principal", 1434, 1097],
] as const;
export default function Home() { return <main>
  <header className="nav shell"><a className="brand" href="#inicio">Live Bucaramanga</a><nav aria-label="Navegación principal"><a href="#historia">Historia</a><a href="#espacios">Espacios</a><Link href="/vida-en-bucaramanga">Guía local</Link><Link className="langSwitch" href="/en">EN</Link><ContactNavLink/></nav></header>
  <section className="hero" id="inicio"><img src="/casa/fachada-atardecer.webp" alt="Casa en venta en Altos de Cabecera, Bucaramanga" width="1448" height="1086" fetchPriority="high" decoding="async"/></section>
  <section className="heroIntro"><div className="shell"><p className="eyebrow">Cabecera del Llano · Bucaramanga</p><h1><span className="seoTitle">Casa en venta en Altos de Cabecera, Bucaramanga</span><em>Una casa con historia.<br/>Un nuevo comienzo.</em></h1><p className="lead">Después de más de 30 años en nuestra familia, buscamos a quien quiera imaginar su próxima etapa.</p><div className="actions"><a className="button primary" href="#espacios">Conocer la casa</a><a className="button outline" href="#recorrido">Ver recorrido</a></div></div></section>
  <section className="listingSummary"><div className="shell summaryGrid"><div className="summaryPrice"><span>Valor de venta</span><strong>$1.800 millones</strong></div><div className="propertySpecs">{propertySpecs.map(([icon,value,label])=><div className="propertySpec" key={label}><SpecIcon name={icon}/><strong>{value}</strong><span>{label}</span></div>)}</div><a className="summaryCta" href="#contacto">Solicitar información</a></div></section>
  <section className="story shell" id="historia"><div><p className="eyebrow">Desde 1992</p><h2>Una casa para hacerla tuya.<br/>Espacios para vivirla a tu manera.</h2></div><div className="storyText"><p>Mi madre llegó aquí en 1992. En estas habitaciones hubo conversaciones largas, visitas, música y muchos momentos cotidianos que se convirtieron en recuerdos.</p><p>Hoy la casa abre una nueva posibilidad: conservar lo que tiene carácter y transformar sus espacios para crear un lugar propio, amplio y bien pensado.</p><p className="signature">— La familia propietaria</p></div></section>
  <section className="addressMeaning"><div className="addressMeaningInner shell"><div className="addressNumber" aria-hidden="true">41·111</div><div className="addressMeaningCopy"><p className="eyebrow">La dirección</p><h2>41·111: una dirección con significado.</h2><p>Durante años nos ha llamado la atención la forma en que se repiten los números de esta casa. 41–111 puede leerse como 4 | 11 | 11: el cuatro habla de hogar, estructura, estabilidad y raíces; los cuatro unos evocan identidad, iniciativa y nuevos comienzos; y el 11:11 se interpreta en la numerología y en corrientes espirituales como la de Kryon como un símbolo de intuición, transición y apertura hacia una nueva etapa. Al sumar todos sus dígitos, el resultado es ocho, un número que suele asociarse con la propiedad, la administración y la capacidad de convertir una idea en algo concreto.</p><p>Para nuestra familia no es una promesa ni una fórmula. Es una coincidencia bonita que parece acompañar la historia de esta casa: un lugar construido sobre raíces firmes que ahora espera nuevas ideas, nuevos habitantes y un nuevo capítulo.</p></div></div></section>
  <section className="mamaSection"><div className="mamaStory shell"><div className="mamaPortrait"><img src="/casa/mama-johanna-patio.webp" alt="Madre e hija en el jardín interior de la casa" width="946" height="1662" loading="lazy"/></div><div className="mamaCopy"><p className="eyebrow">La casa de mi mamá</p><h2>Una casa que la acompañó durante 34 años.</h2><p>Mi mamá llegó aquí en 1992. Durante muchos años, sus niveles y escaleras fueron parte de su rutina diaria y la ayudaron a mantenerse activa e independiente.</p><p>Hoy tiene 91 años y trasladarse entre los distintos niveles ya es difícil para ella. La decisión de vender nace de buscar un hogar que se ajuste mejor a esta etapa: cómodo, seguro y fácil de recorrer.</p><p>Nos gustaría que esta casa continúe siendo un lugar vivido, cuidado y lleno de nuevos momentos.</p></div></div></section>
  <section className="factsWrap"><div className="facts shell">{facts.map(([n,l])=><div className="fact" key={n}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
  <section className="possibility shell"><div className="possibilityImage"><img src="/casa/entrada-luces-calidas.webp" alt="Entrada y terraza de la casa" width="1536" height="1024"/></div><div className="possibilityCopy"><p className="eyebrow">Una casa para reinterpretar</p><h2>Espacio, carácter y múltiples caminos.</h2><p>Su distribución en diferentes niveles, los patios y las áreas generosas permiten pensarla como vivienda familiar renovada o explorar otros usos compatibles. También existen espacios actualmente desaprovechados cuya redistribución podría estudiarse con un arquitecto.</p><ul><li>Vivienda para varias generaciones</li><li>Estudio, consultorio u oficinas de escala doméstica</li><li>Alojamiento boutique o renta de corta estancia</li><li>Local comercial actualmente arrendado</li><li>Espacio exterior para dos vehículos de tamaño estándar o uno grande, sin obstruir el local</li></ul><small>El espacio exterior no corresponde a parqueaderos privados. Todo uso distinto al residencial y cualquier modificación deberán validarse previamente mediante estudios técnicos y ante las autoridades competentes.</small></div></section>
  <section className="gallerySection" id="espacios"><div className="shell"><p className="eyebrow">Los espacios</p><div className="sectionTitle"><h2>La casa y sus posibilidades.</h2><p>Las fotografías corresponden a los espacios reales de la propiedad.</p></div><div className="gallery">{gallery.map(([src,alt,w,h],i)=><figure className={i===0||i===3||i===8?"wide":""} key={src}><img src={src} alt={alt} width={w} height={h} loading="lazy" decoding="async"/></figure>)}</div></div></section>
  <section className="memoriesSection"><div className="shell"><p className="eyebrow">La vida que sucedió aquí</p><div className="memoriesIntro"><h2>Celebraciones, visitas y muchos días compartidos.</h2><p>Estas imágenes muestran la casa como realmente la vivimos: un lugar de encuentros familiares, flores, conversaciones alrededor de la mesa y momentos sencillos que quedaron en nuestra memoria.</p></div><div className="memoriesGrid"><figure><img src="/casa/mama-patio.webp" alt="La propietaria en el jardín interior de la casa" width="922" height="1706" loading="lazy"/></figure><figure><img src="/casa/mama-terraza.webp" alt="La propietaria en una de las terrazas de la casa" width="1098" height="1378" loading="lazy"/></figure><figure><img src="/casa/mama-flores.webp" alt="Celebración familiar con flores dentro de la casa" width="1378" height="1372" loading="lazy"/></figure><div className="memoryVideo"><YouTubeVideo videoId="LFaoiRJChes" title="Momentos compartidos en Casa 41·111" poster="/casa/mama-flores.webp" vertical/></div></div></div></section>
  <section className="videoSection shell" id="recorrido"><p className="eyebrow">Recorre la casa</p><div className="sectionTitle"><h2>Mírala con más calma.</h2><p>Un recorrido para conocer la distribución y la amplitud de sus espacios.</p></div><div className="videos singleVideo"><YouTubeVideo videoId="6CrgWXJBg2I" title="Recorrido completo de Casa 41·111" poster="/casa/sala-principal.webp"/></div></section>
  <section className="locationSection"><div className="location shell"><div className="locationCopy"><p className="eyebrow">La ubicación</p><h2>Altos de Cabecera</h2><p>Una zona consolidada de Bucaramanga, cerca de los servicios de Cabecera, comercios, parques y vida de barrio.</p><span>Carrera 40 # 41–111 · Bucaramanga, Santander</span><a className="mapLink" href="https://www.google.com/maps/search/?api=1&amp;query=Carrera%2040%20%2341-111%2C%20Bucaramanga%2C%20Santander%2C%20Colombia" target="_blank" rel="noreferrer">Abrir en Google Maps</a></div><div className="locationMap"><iframe title="Ubicación de Casa 41-111 en Altos de Cabecera" src="https://www.google.com/maps?q=Carrera%2040%20%2341-111%2C%20Bucaramanga%2C%20Santander%2C%20Colombia&amp;output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></section>
  <section className="trailsSection"><div className="shell trailsIntro"><div><p className="eyebrow">Caminatas desde la casa</p><h2>Varias rutas para caminar, muy cerca de casa.</h2></div><p>El mapa muestra la cercanía de diferentes parques, senderos y recorridos para elegir: Parque de Los Leones, Parque de los Perros —Enrique Viviescas—, Bosque Encantado, Bosque de los Caminantes, Parque del Agua, Parque La Flora y rutas hacia los cerros orientales. Desde muy temprano es habitual ver a los residentes caminando y haciendo ejercicio por el sector.</p></div><div className="shell trailsMap"><img src="/casa/mapa-senderos-altos-cabecera.webp" alt="Mapa con varias rutas para caminar, parques y senderos cercanos a Casa 41-111 en Altos de Cabecera" width="1800" height="886" loading="lazy"/></div></section>
  <section className="guidePreview"><div className="shell"><p className="eyebrow">Vida en Bucaramanga</p><div className="guidePreviewTitle"><h2>Conoce la ciudad desde la vida cotidiana.</h2><Link href="/vida-en-bucaramanga">Ver los {spanishArticles.length} artículos</Link></div><div className="guidePreviewGrid"><Link href="/vida-en-bucaramanga/vivir-en-altos-de-cabecera"><span>01</span><h3>Vivir en Altos de Cabecera</h3><p>Ubicación, movilidad, universidad y servicios cercanos.</p></Link><Link href="/vida-en-bucaramanga/plazas-de-mercado-de-bucaramanga"><span>02</span><h3>Plazas de mercado</h3><p>Guarín, La Rosita, La Concordia, San Francisco y Central.</p></Link><Link href="/vida-en-bucaramanga/caminatas-parques-y-senderos"><span>03</span><h3>Caminatas y senderos</h3><p>Parques y recorridos que comienzan cerca de la casa.</p></Link></div></div></section>
  <FaqSection/>
  <section className="contactSection" id="contacto"><div className="contact shell"><p className="eyebrow">Venta directa</p><h2>¿Te imaginas aquí?</h2><p>Cuéntanos qué ves en esta casa y conversemos directamente, sin intermediarios.</p><ContactForm/></div></section>
  <footer className="shell"><span>Live Bucaramanga · Casa 41·111</span><span>Venta directa por sus propietarios · Bucaramanga</span></footer>
  <a className="whatsappFloat" href="https://wa.me/573126084753?text=Hola%2C%20quisiera%20informaci%C3%B3n%20sobre%20la%20Casa%2041-111" target="_blank" rel="noreferrer" aria-label="Escribir por WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.4L3 20.5l1.4-4.7a8.5 8.5 0 1 1 16.1-4.1Z"/><path d="M8.1 7.5c.2-.5.5-.5.8-.5h.5c.2 0 .4.1.5.4l.7 1.7c.1.3 0 .5-.2.7l-.6.7c-.2.2-.1.4 0 .6.7 1.3 1.8 2.4 3.2 3 .2.1.4.1.6-.1l.8-1c.2-.2.4-.3.7-.2l1.8.8c.3.1.4.3.4.5 0 .3-.2 1.5-.8 2-.5.5-1.4.8-2.3.6-1.1-.2-2.6-.8-4.4-2.4-2.1-1.8-3.4-4.1-3.6-5.3-.2-.7.1-1.2.4-1.5.3-.3.6-.5.7-.5"/></svg><span>WhatsApp</span></a>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"SingleFamilyResidence","@id":`${siteUrl}/#property`,url:`${siteUrl}/`,name:"Casa 41·111",description:"Casa familiar amplia en venta directa en Altos de Cabecera, Bucaramanga.",image:[`${siteUrl}/casa/fachada-atardecer.webp`,`${siteUrl}/casa/sala-principal.webp`,`${siteUrl}/casa/patio-luces.webp`],numberOfBedrooms:7,numberOfBathroomsTotal:6,floorSize:{"@type":"QuantitativeValue",value:540,unitCode:"MTK"},address:{"@type":"PostalAddress",streetAddress:"Carrera 40 # 41-111",addressLocality:"Bucaramanga",addressRegion:"Santander",addressCountry:"CO"},offers:{"@type":"Offer",url:`${siteUrl}/`,price:1800000000,priceCurrency:"COP",availability:"https://schema.org/InStock",seller:{"@type":"Person",name:"Familia propietaria de Casa 41·111"}}})}}/>
</main> }
