import type { Metadata } from "next";
import Link from "next/link";
import ContactForm from "../contact-form";
import ContactNavLink from "../contact-nav-link";
import FaqSection from "../faq-section";
import { englishArticles } from "../articles";
import YouTubeVideo from "../youtube-video";

export const metadata: Metadata = {
  title: "House for Sale in Altos de Cabecera, Bucaramanga | Casa 41·111",
  description: "A spacious seven-bedroom family house for sale directly by its owners in Altos de Cabecera, Bucaramanga, with renovation and boutique accommodation potential.",
  alternates: { canonical: "/en", languages: { "es-CO": "/", en: "/en" } },
  openGraph: { title: "Casa 41·111 | House for Sale in Bucaramanga", description: "A spacious family home in Altos de Cabecera, offered directly by its owners.", url: "/en", locale: "en_US", type: "website", images: [{ url: "/casa/fachada-atardecer.webp", alt: "Casa 41-111 in Altos de Cabecera at sunset" }] }
};

const facts = [
  ["264.87 m²", "cadastral lot area"], ["Service suite", "independent bedroom and bathroom"],
  ["Terrace", "with an interior garden"], ["Commercial unit", "currently rented"],
];
const propertySpecs = [
  ["levels", "5", "levels"], ["bed", "7", "bedrooms"],
  ["bath", "6", "bathrooms"], ["area", "540 m²", "built area"],
] as const;

function SpecIcon({name}:{name:typeof propertySpecs[number][0]}) {
  if(name==="levels") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 15 8 4 8-4M4 10l8 4 8-4M4 5l8 4 8-4-8-4-8 4Z"/></svg>;
  if(name==="bed") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 18v-8m18 8v-6a2 2 0 0 0-2-2H9a3 3 0 0 0-3 3v5m0-8V7h5a2 2 0 0 1 2 2v1M3 15h18M5 21v-3m14 3v-3"/></svg>;
  if(name==="bath") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 13h16v2a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5v-2Zm2 0V6a3 3 0 0 1 6 0M7 20l-1 2m11-2 1 2"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V8h16v12H4Zm4 0v-6h8v6M2 8l10-5 10 5M8 10h.01M12 10h.01M16 10h.01"/></svg>;
}
const gallery = [
  ["/casa/fachada-cielo-azul.webp", "Daytime façade of the house"],
  ["/casa/entrada-luces-calidas.webp", "Main entrance, terrace and plants"],
  ["/casa/sala-principal.webp", "Main living room with family furniture"],
  ["/casa/sala-complementaria.webp", "Additional view of the living room"],
  ["/casa/cocina-principal.webp", "Kitchen, breakfast table and timber ceiling"],
  ["/casa/cocina-complementaria.webp", "General view of the kitchen"],
  ["/casa/cocina-mesones.webp", "Kitchen counters and work area"],
  ["/casa/patio-luces.webp", "Interior garden with warm lighting"],
  ["/casa/terraza-atardecer.webp", "Outdoor terrace at sunset"],
  ["/casa/habitacion-principal.webp", "Main bedroom"],
];

export default function EnglishHome() { return <main lang="en">
  <header className="nav shell"><Link className="brand" href="/en#home">Casa 41·111</Link><nav aria-label="Main navigation"><a href="#story">Story</a><a href="#spaces">Spaces</a><Link href="/en/living-in-bucaramanga">Local guide</Link><Link className="langSwitch" href="/">ES</Link><ContactNavLink lang="en"/></nav></header>
  <section className="hero" id="home"><img src="/casa/fachada-atardecer.webp" alt="Casa 41-111 in Altos de Cabecera at sunset"/></section>
  <section className="heroIntro"><div className="shell"><p className="eyebrow">Altos de Cabecera · Bucaramanga</p><h1>A home with a story.<br/><em>A new beginning.</em></h1><p className="lead">After more than 30 years in our family, we are looking for someone ready to imagine its next chapter.</p><div className="actions"><a className="button primary" href="#spaces">Explore the house</a><a className="button outline" href="#tour">Watch the tour</a></div></div></section>
  <section className="listingSummary"><div className="shell summaryGrid"><div className="summaryPrice"><span>Asking price</span><strong>COP $1.8 billion</strong></div><div className="propertySpecs">{propertySpecs.map(([icon,value,label])=><div className="propertySpec" key={label}><SpecIcon name={icon}/><strong>{value}</strong><span>{label}</span></div>)}</div><a className="summaryCta" href="#contact">Request information</a></div></section>
  <section className="story shell" id="story"><div><p className="eyebrow">Since 1992</p><h2>A home to make your own.<br/>Space to live it your way.</h2></div><div className="storyText"><p>My mother moved here in 1992. These rooms held long conversations, visits, music and the ordinary moments that became family memories.</p><p>The house now offers a new possibility: preserve what gives it character and transform its generous spaces into a private, carefully considered home.</p><p className="signature">— The owner’s family</p></div></section>
  <section className="addressMeaning"><div className="addressMeaningInner shell"><div className="addressNumber" aria-hidden="true">41·111</div><div className="addressMeaningCopy"><p className="eyebrow">The address</p><h2>41·111: an address with meaning.</h2><p>Over the years, our family has always noticed the repetition in this house number. 41–111 can be read as 4 | 11 | 11: four speaks of home, structure, stability and roots; the four ones evoke identity, initiative and new beginnings; and 11:11 is interpreted in numerology and spiritual traditions including Kryon as a symbol of intuition, transition and openness to a new stage. The sum of all its digits is eight, a number often associated with property, stewardship and the ability to turn an idea into something tangible.</p><p>For our family, it is neither a promise nor a formula. It is simply a beautiful coincidence that seems to accompany the story of this house: a place built on strong roots, now waiting for new ideas, new residents and a new chapter.</p></div></div></section>
  <section className="mamaSection"><div className="mamaStory shell"><div className="mamaPortrait"><img src="/casa/mama-johanna-patio.webp" alt="Mother and daughter in the interior garden" loading="lazy"/></div><div className="mamaCopy"><p className="eyebrow">My mother’s home</p><h2>A house that accompanied her for 34 years.</h2><p>My mother arrived in 1992. For many years, the levels and staircases were part of her daily routine and helped her remain active and independent.</p><p>She is now 91, and moving between levels has become difficult. Selling is part of finding a home that fits this stage of her life: comfortable, safe and easy to navigate.</p><p>We hope this house will continue to be lived in, cared for and filled with new moments.</p></div></div></section>
  <section className="factsWrap"><div className="facts shell">{facts.map(([n,l])=><div className="fact" key={n}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
  <section className="possibility shell"><div className="possibilityImage"><img src="/casa/entrada-luces-calidas.webp" alt="House entrance and terrace"/></div><div className="possibilityCopy"><p className="eyebrow">A home to reinterpret</p><h2>Space, character and several possible paths.</h2><p>The multilevel layout, patios and generous rooms can support a renovated family home or other compatible uses. An architect could also study how underused areas might be reorganized.</p><ul><li>A multigenerational family home</li><li>A private office or professional workspace</li><li>Boutique accommodation or short stays</li><li>A currently rented commercial unit</li><li>Exterior space for two standard vehicles or one larger vehicle without obstructing the commercial unit</li></ul><small>The exterior space is not private parking. Non-residential uses and alterations must be assessed by qualified professionals and verified with the relevant authorities.</small></div></section>
  <section className="gallerySection" id="spaces"><div className="shell"><p className="eyebrow">The spaces</p><div className="sectionTitle"><h2>The house and its possibilities.</h2><p>The photographs show the property’s real spaces.</p></div><div className="gallery">{gallery.map(([src,alt],i)=><figure className={i===0||i===3||i===8?"wide":""} key={src}><img src={src} alt={alt}/></figure>)}</div></div></section>
  <section className="memoriesSection"><div className="shell"><p className="eyebrow">Life in this house</p><div className="memoriesIntro"><h2>Celebrations, visits and many shared days.</h2><p>These images show the house as we lived in it: family gatherings, flowers, conversations around the table and simple moments that stayed with us.</p></div><div className="memoriesGrid"><figure><img src="/casa/mama-patio.webp" alt="The owner in the interior garden" loading="lazy"/></figure><figure><img src="/casa/mama-terraza.webp" alt="The owner on one of the terraces" loading="lazy"/></figure><figure><img src="/casa/mama-flores.webp" alt="A family celebration inside the house" loading="lazy"/></figure><div className="memoryVideo"><YouTubeVideo videoId="LFaoiRJChes" title="Moments shared at Casa 41·111" poster="/casa/mama-flores.webp" vertical/></div></div></div></section>
  <section className="videoSection shell" id="tour"><p className="eyebrow">Walk through the house</p><div className="sectionTitle"><h2>Take a closer look.</h2><p>A video tour showing the layout and generous proportions of the house.</p></div><div className="videos singleVideo"><YouTubeVideo videoId="6CrgWXJBg2I" title="Full tour of Casa 41·111" poster="/casa/sala-principal.webp"/></div></section>
  <section className="locationSection"><div className="location shell"><div className="locationCopy"><p className="eyebrow">Location</p><h2>Altos de Cabecera</h2><p>A well-established part of Bucaramanga, close to Cabecera’s services, shops, parks and everyday neighborhood life.</p><span>Carrera 40 # 41–111 · Bucaramanga, Santander</span><a className="mapLink" href="https://www.google.com/maps/search/?api=1&amp;query=Carrera%2040%20%2341-111%2C%20Bucaramanga%2C%20Santander%2C%20Colombia" target="_blank" rel="noreferrer">Open in Google Maps</a></div><div className="locationMap"><iframe title="Location of Casa 41-111 in Altos de Cabecera" src="https://www.google.com/maps?q=Carrera%2040%20%2341-111%2C%20Bucaramanga%2C%20Santander%2C%20Colombia&amp;output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></section>
  <section className="trailsSection"><div className="shell trailsIntro"><div><p className="eyebrow">Walks from the house</p><h2>Several walking routes, all close to home.</h2></div><p>The map shows a variety of nearby parks, trails and walking routes to choose from: Los Leones Park, Enrique Viviescas Park, Bosque Encantado, Bosque de los Caminantes, Parque del Agua, La Flora Park and routes toward Bucaramanga’s eastern hills. Residents begin walking and exercising from the early hours of the morning.</p></div><div className="shell trailsMap"><img src="/casa/mapa-senderos-altos-cabecera.webp" alt="Map showing several walking routes, parks and trails near Casa 41-111" loading="lazy"/></div></section>
  <section className="guidePreview"><div className="shell"><p className="eyebrow">Living in Bucaramanga</p><div className="guidePreviewTitle"><h2>Discover the city through everyday life.</h2><Link href="/en/living-in-bucaramanga">View all {englishArticles.length} articles</Link></div><div className="guidePreviewGrid"><Link href="/en/living-in-bucaramanga/living-in-altos-de-cabecera"><span>01</span><h3>Living in Altos de Cabecera</h3><p>Location, mobility, the university and nearby services.</p></Link><Link href="/en/living-in-bucaramanga/food-markets-in-bucaramanga"><span>02</span><h3>Local food markets</h3><p>Guarín, La Rosita, La Concordia, San Francisco and Central.</p></Link><Link href="/en/living-in-bucaramanga/walks-parks-and-trails"><span>03</span><h3>Walks and trails</h3><p>Parks and routes that begin close to the house.</p></Link></div></div></section>
  <FaqSection lang="en"/>
  <section className="contactSection" id="contact"><div className="contact shell"><p className="eyebrow">Direct sale</p><h2>Can you imagine yourself here?</h2><p>Tell us what you see in this house and speak directly with the owners.</p><ContactForm lang="en"/></div></section>
  <footer className="shell"><span>Casa 41·111</span><span>For sale directly by its owners · Bucaramanga</span></footer>
  <a className="whatsappFloat" href="https://wa.me/573126084753?text=Hello%2C%20I%20would%20like%20information%20about%20Casa%2041-111" target="_blank" rel="noreferrer" aria-label="Write on WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.4L3 20.5l1.4-4.7a8.5 8.5 0 1 1 16.1-4.1Z"/><path d="M8.1 7.5c.2-.5.5-.5.8-.5h.5c.2 0 .4.1.5.4l.7 1.7c.1.3 0 .5-.2.7l-.6.7c-.2.2-.1.4 0 .6.7 1.3 1.8 2.4 3.2 3 .2.1.4.1.6-.1l.8-1c.2-.2.4-.3.7-.2l1.8.8c.3.1.4.3.4.5 0 .3-.2 1.5-.8 2-.5.5-1.4.8-2.3.6-1.1-.2-2.6-.8-4.4-2.4-2.1-1.8-3.4-4.1-3.6-5.3-.2-.7.1-1.2.4-1.5.3-.3.6-.5.7-.5"/></svg><span>WhatsApp</span></a>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"SingleFamilyResidence",name:"Casa 41·111",description:"A spacious family home for sale in Altos de Cabecera, Bucaramanga.",numberOfBedrooms:7,numberOfBathroomsTotal:6,floorSize:{"@type":"QuantitativeValue",value:540,unitCode:"MTK"},address:{"@type":"PostalAddress",streetAddress:"Carrera 40 # 41-111",addressLocality:"Bucaramanga",addressRegion:"Santander",addressCountry:"CO"},offers:{"@type":"Offer",price:1800000000,priceCurrency:"COP",availability:"https://schema.org/InStock"}})}}/>
  </main> }
